### PR TITLE
added GH action

### PR DESCRIPTION
**Pull request by rishvantsingh**
#5 Updated the repo with GH action.
Please update and review the PR.

### CODE REVIEW

**Comment by AlvinKuruvilla** [comment]
@rishvantsingh Thanks for your great work. See the comment I made, once that is addressed I can merge it. Great work 👍🏽

**Comment by rishvantsingh** [comment]
Thankyou so much @AlvinKuruvilla

**Comment by rishvantsingh** [comment]
HI @AlvinKuruvilla . Where have you commented?

**Comment by AlvinKuruvilla** [comment]
Check the PR on GitHub I have made a comment that for this project I am using the black formatted not flake8 so I was wondering if you could change that in the workflow

**Comment by rishvantsingh** [comment]
Hi @AlvinKuruvilla . I have updated the workflow as per your need. Please review and merge it.

**Review by AlvinKuruvilla — APPROVED** [review]

**Pull request merged**
